services:
  nginx:
    image: ghcr.io/nginxinc/nginx-unprivileged:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "443:443/udp"   # HTTP/3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - api

  api:
    image: mendhak/http-https-echo:39
    container_name: api
    environment:
    - HTTP_PORT=3000
    expose:
      - "3000"


  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/cloudflare.ini:/etc/cloudflare.ini:ro
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare.ini -d terraform.martinn.no --agree-tos -n -m admin@terraform.martinn.no